global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka'
    eureka_sd_configs:
    - server: http://@localhost:8761/eureka
    - basic_auth:
      username: 'admin'
      password: 'password'
    relabel_configs:
    - source_labels: [__meta_eureka_app_name]
      target_label: application
    - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
      target_label: __metrics_path__
    - source_labels: [__address__]
      target_label: instance